export * from './addTestingToEducationalSpaceCatalog.request.dto';
export * from './createEducationalSpace.request.dto';
export * from './createUser.request.dto';
export * from './deleteEntityById.request.dto';
export * from './launchTesting.request.dto';
export * from './refreshToken.dto';
export * from './setMyPassword.request.dto';
export * from './updateAccessScope.request.dto';
export * from './useInviteLink.dto';
